# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- task: RedgateSqlChangeAutomationBuild@3
  inputs:
    operation: 'Build'
    dbFolder: 'SubFolder'
    subFolderPath: 'dbcode'
    packageName: 'ASimpleTalkDBPkg'
    tempServerTypeBuild: 'sqlServer'
    tempServerNameBuild: '.\SQL2017'
    authMethodBuild: 'sqlServerAuth'
    usernameBuild: '$(BuildLogin)'
    passwordBuild: '$(BuildPassword)'
    nugetPackageVersionSelector: 'Specific'
    nugetPackageVersion: '1.0'
    requiredVersionOfDlma: 'latest'